import React, { Component } from "react";

/**
 * Creates a scoreboard to display top ten high scores
 */
class Scoreboard extends Component {
    constructor(props){
        super(props);
        this.state = {
            highscores: [props],
            scoreboard: "none",
            scoreString: ""
        };
        this.showTopTen = this.showTopTen.bind(this);
    };

    /**
     * Converts highscore array into list to be displayed on scoreboard
     * @returns {string} format --> player name: score
     */
    showTopTen = () => {
        let list = "<!--autogenerated by showTopTen --> \n";
        for(let i = 0; i < this.state.highscores.length; i++){
            list += <li> + {this.state.highscores[i]} + ":" + {this.state.highscores[i]} + </li> + "\n";
        }
        console.log(this.state.scoreString);
        this.setState({scoreString: list});
    };
    render(){
        return (
        <div style = {{
            position: "absolute",
            alignItems: "center",
            top: 125,
            left: 0,
            right: 0,
            margin: "auto",
            height: 300,
            width: 300,
            zIndex: 3,
            display: this.props.scoreboard,
            boxShadow: "1px 1px 1px 1px #08415C",
            borderRadius: "10px",
            textAlign: "left",
            fontSize: "large",
            fontFamily: "Georgia",
            color: "white",
            padding: 20
        }} className="primaryBg">
            <h3 style = {{textAlign: "center"}}>High Scores</h3>
           <ol type = "1">
               {this.state.highscores}
               </ol>

        </div>
        )
    }
}

export default Scoreboard;